// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI3qcoLPk6vBTuVncughEZ-6hwBRqwIGQ',
    appId: '1:833739885993:web:e16241344747849c9108b8',
    messagingSenderId: '833739885993',
    projectId: 'micro-harmony-405004',
    authDomain: 'micro-harmony-405004.firebaseapp.com',
    storageBucket: 'micro-harmony-405004.appspot.com',
    measurementId: 'G-C66JG9F3BP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIJ3eDYVZtIR37LKXjbeGikEcOuZvHtWc',
    appId: '1:833739885993:android:2dcb67d6a82dedff9108b8',
    messagingSenderId: '833739885993',
    projectId: 'micro-harmony-405004',
    storageBucket: 'micro-harmony-405004.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkHGGhQqlv-DCWXIoJ2RyMQBCzxumR33g',
    appId: '1:833739885993:ios:77300d99da8e465a9108b8',
    messagingSenderId: '833739885993',
    projectId: 'micro-harmony-405004',
    storageBucket: 'micro-harmony-405004.appspot.com',
    iosBundleId: 'com.example.myNewApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkHGGhQqlv-DCWXIoJ2RyMQBCzxumR33g',
    appId: '1:833739885993:ios:bf351a13ccf010539108b8',
    messagingSenderId: '833739885993',
    projectId: 'micro-harmony-405004',
    storageBucket: 'micro-harmony-405004.appspot.com',
    iosBundleId: 'com.example.myNewApp.RunnerTests',
  );
}
